SigninLogs
| where UserId contains "d57de9bd-cf2d-4e98-a49c-4d98f15b47b0"
| extend parsedData = parse_json(DeviceDetail)
| extend deviceId = tostring(parsedData.deviceId)
| extend deviceName = tostring(parsedData.displayName)
| extend compliancy = tostring(parsedData.isCompliant)
| extend managed = tostring(parsedData.isManaged)
| extend operatingSystem = tostring(parsedData.operatingSystem)
| extend browser = tostring(parsedData.browser)
| project-away DeviceDetail, parsedData
| project TimeGenerated, Identity, OperationName, ResultType, ResultSignature, ResultDescription, IPAddress, Location, ResourceDisplayName, AppDisplayName, deviceId, operatingSystem, browser, deviceName, compliancy, managed
